server:
  port: 8082
spring:
  flyway:
    table: amc_schema_version
    locations:
      - classpath:db/migration/{vendor}
    enabled: true
    baseline-version: 1
    baseline-on-migrate: false
    check-location: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      show-sql: true
      hbm2ddl: auto
  datasource:
#-------------------for postgres --------------
    url: jdbc:postgresql://127.0.0.1:5432/amc
    platform: postgresql
#-------------------for h2 --------------------
#    url: jdbc:h2:./amc
#    platform: h2
    username: amc
    password: amc